# Site settings
title: "Better late than never!!!"
header-img: img/home-bg.png
email: brandondecarlo@live.com
copyright_name: DownsideupmediaUSA
description: > # this means to ignore newlines until "baseurl:"
   "The long and windy road that lead me to the world of Programming"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DownsideupmediaUSA
learn_profile: DownsideupmediaUSA
email_username: brandondecarlo@live.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
